### ISSUE TITLE
Tweet YouTube uploads

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#22]
It would be great to send out a tweet from LNUG when a new video is uploaded to youtube.

The tweet should reference the video and the speaker.

Can we use zappier?

**Comment by iancrowther** [comment]
bonus points for getting a link to slides as wel

maybe ask speakers to post slide link in common place and x-ref that.  maybe the Github issue?

**Comment by bencevans** [comment]
Prob best not use an automated feed so videos can be checked before published on LNUG feeds. We could maintain the archive in some sort of computer readable format...  JSON might be a bit eww if edited by hand, YAML idea...

## Proposed Repo: lnug/archive

### [year]-[month]-[day].yml

```yml
- title: ESaBillion
  speakers:
    - name: Professor Elemental
      url: http://professorelemental.com/
  video_url: https://www.youtube.com/watch?v=0iRTB-FTMdk
  slides_url: https://www.speakerdeck.com/blahblah


# Multi Speakers (Not sure if this happens O.o)

- title: Blowing Node Up
  speakers:
    - name: Colin Furze
      url: http://www.colinfurze.com/
    - name: Jazzy Guest Speaker
      url: http://www.leekspin.com/
  video_url: https://www.youtube.com/watch?v=bKHz7wOjb9w
  slides_url: https://www.speakerdeck.com/blahblah
```
